<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.11</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <repositories>
        <repository>
            <id>spring-releases</id>
            <name>Spring Releases</name>
            <url>https://repo.spring.io/release</url>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
        </repository>
    </repositories>

    <groupId>com.ods</groupId>
    <artifactId>user_authentication</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>user_authentication</name>
    <description>Open Dataspaces project for Spring Boot</description>
    <url/>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>LICENSE</url>
            <distribution>manual</distribution>
        </license>
    </licenses>

    <developers>
        <developer/>
    </developers>

    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>

    <properties>
        <java.version>21</java.version>
        <!-- Default severity level for Checkstyle; can be overridden by command line or profiles -->
        <org.checkstyle.google.severity>warning</org.checkstyle.google.severity>
        <org.checkstyle.google.suppressionfilter.config>config/checkstyle/checkstyle-suppressions.xml</org.checkstyle.google.suppressionfilter.config>
    </properties>

    <modules>
        <module>core</module>
    </modules>

    <dependencyManagement>
        <dependencies>

            <!-- Core module dependency -->
            <dependency>
                <groupId>com.ods</groupId>
                <artifactId>core</artifactId>
                <version>0.0.1-SNAPSHOT</version>
                <classifier>plain</classifier>
            </dependency>

            <!-- Keycloak clients -->
            <dependency>
                <groupId>org.keycloak</groupId>
                <artifactId>keycloak-admin-client</artifactId>
                <version>26.0.3</version>
            </dependency>
            <dependency>
                <groupId>org.keycloak</groupId>
                <artifactId>keycloak-authz-client</artifactId>
                <version>26.0.3</version>
            </dependency>

            <!-- PostgreSQL database driver -->
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>42.7.1</version>
            </dependency>

            <!-- Lombok -->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.38</version>
                <scope>provided</scope>
            </dependency>

            <!-- Masking annotation -->
            <dependency>
                <groupId>org.reflections</groupId>
                <artifactId>reflections</artifactId>
                <version>0.10.2</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <configLocation>config/checkstyle/checkstyle-google-customization.xml</configLocation>
                    <includeTestSourceDirectory>true</includeTestSourceDirectory>
                    <propertyExpansion>
                        org.checkstyle.google.severity=${org.checkstyle.google.severity}
                        org.checkstyle.google.suppressionfilter.config=${org.checkstyle.google.suppressionfilter.config}
                    </propertyExpansion>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>com.puppycrawl.tools</groupId>
                        <artifactId>checkstyle</artifactId>
                        <version>10.25.0</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>checkstyle-generated</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <!-- Default profile to copy dependencies during install phase -->
            <id>default</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <!-- Dependency Plugin -->
                        <!-- To ensure dependencies are copied because classpath may not be recognized correctly when debugging in a local environment -->
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <version>3.6.0</version>
                        <executions>
                            <execution>
                            <id>copy-dependencies</id>
                            <phase>install</phase>
                            <goals>
                                <goal>copy-dependencies</goal>
                            </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <!-- Profile for GitHub CI -->
            <id>github-ci</id>

            <!-- skip copying dependencies -->

        </profile>

        <profile>
            <!-- Profile for strict Checkstyle enforcement -->
            <id>checkstyle</id>
            <properties>
                <org.checkstyle.google.severity>error</org.checkstyle.google.severity>
            </properties>
        </profile>
    </profiles>
</project>
