# KeyCloak settings
keycloak.realm=master
keycloak.api-endpoint=http://[::1]:8081

# credentials settings
keycloak.credentials.admin-realm=master
keycloak.credentials.admin-username=admin
keycloak.credentials.admin-password=password
keycloak.credentials.admin-client-id=admin-cli

# authorization settings
keycloak.authorization.url=http://[::1]:8081
keycloak.authorization.response-type=code
keycloak.authorization.scope=openid
keycloak.authorization.code-challenge-method=S256

# Hibernate Dialect settings
spring.sql.init.mode=always

## DEBUG INFO WARN
# Application log level (TRACE/DEBUG/INFO/WARN)
logging.level.com.ods.*=DEBUG
# Log level
logging.level.org.springframework.web=debug
logging.level.org.springframework.web.cors=debug
# PostgreSQL log level
logging.level.org.postgresql=DEBUG

# Enable ANSI colors in the console output
spring.output.ansi.enabled=always

# Database SSL settings
ods.database-ssl=false
ods.database-ssl-mode=disable
