# -----------------------------------------
# System properties
# -----------------------------------------
spring.application.name=user_authentication
# Disable Spring Boot's default error handler
server.error.whitelabel.enabled=false
server.error.path=/error
# Disable static resource mappings
spring.web.resources.add-mappings=false
# Enable Open-In-View to prevent database queries during view rendering, to suppress runtime warning
spring.jpa.open-in-view=true
# DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property.
spring.jpa.hibernate.ddl-auto=none
# Hibernate Dialect settings (always/never/embedded)
spring.sql.init.mode=never
# Relaxed characters for Tomcat to allow [] in path variables
server.tomcat.relaxed-path-chars=[,]

# -----------------------------------------
# Logging properties
# -----------------------------------------
# log
logging.file.name=${LOGGING_FILE_NAME:logs/user_authentication.log}
# Application log level (TRACE/DEBUG/INFO/WARN)
logging.level.com.ods.*=${LOGGING_LEVEL_COM_ODS:INFO}
# spring framework Log level
logging.level.org.springframework.web=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB:info}
# PostgreSQL log level
logging.level.org.postgresql=${LOGGING_LEVEL_ORG_POSTGRESQL:INFO}
# Show SQL statements in the log
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

# Enable detailed request logging
spring.mvc.log-request-details=${SPRING_MVC_LOG_REQUEST_DETAILS:true}

# Enable ANSI colors in the console output (always/never/detect)
spring.output.ansi.enabled=${SPRING_OUTPUT_ANSI_ENABLED:always}

# -----------------------------------------
# Database properties
# -----------------------------------------
# datasource settings
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/db_ods}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app_ods}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

# -----------------------------------------
# ODS Application properties
# -----------------------------------------
# Application environment name
ods.application-env-name=${ODS_APPLICATION_ENV_NAME:local}
# Enable IP restriction
ods.enable-ip-restriction=${ODS_ENABLE_IP_RESTRICTION:true}
# effective end date default value
ods.default-effective-end-date=${ODS_DEFAULT_EFFECTIVE_END_DATE:9999-12-31}
# Dataabase SSL settings
ods.database-ssl=${ODS_DATABASE_SSL:false}
ods.database-ssl-mode=${ODS_DATABASE_SSL_MODE:disable}
ods.database-ssl-root-cert=${ODS_DATABASE_SSL_ROOT_CERT:}
ods.database-ssl-cert=${ODS_DATABASE_SSL_CERT:}
ods.database-ssl-key=${ODS_DATABASE_SSL_KEY:}

# Enable UC authorization
ods.enable-uc-authorization=${ODS_ENABLE_UC_AUTHORIZATION:true}

# Enable Operator authorization
ods.enable-operator-plant-authorization=${ODS_ENABLE_OPERATOR_PLANT_AUTHORIZATION:true}

# Access Token (JWT) properties
ods.jwt.jwks-cache-duration-second=${ODS_JWT_JWKS_CACHE_DURATION_SECOND:3600}
ods.jwt.jwks-cache-size=${ODS_JWT_JWKS_CACHE_SIZE:10}
ods.jwt.claim-expected-audience=${ODS_JWT_CLAIM_EXPECTED_AUDIENCE:}
ods.jwt.claim-expected-type=${ODS_JWT_CLAIM_EXPECTED_TYPE:Bearer}

# CORS settings
ods.cors.properties-enabled=${ODS_CORS_PROPERTIES_ENABLED:false}
ods.cors.path-pattern=${ODS_CORS_PATH_PATTERN:/**}
ods.cors.allowed-origins=${ODS_CORS_ALLOWED_ORIGINS:http://localhost:3000,https://example.com}
ods.cors.allowed-methods=${ODS_CORS_ALLOWED_METHODS:GET,POST,PUT,OPTIONS}
ods.cors.allowed-headers=${ODS_CORS_ALLOWED_HEADERS:Content-Type,Authorization,API-Key,User-Agent,Accept,Accept-Language,X-TrackingID}
ods.cors.allow-credentials=${ODS_CORS_ALLOW_CREDENTIALS:true}
ods.cors.max-age=${ODS_CORS_MAX_AGE:5}

# -----------------------------------------
# KeyCloak properties
# -----------------------------------------
# KeyCloak settings
keycloak.realm=${KEYCLOAK_REALM:master}
keycloak.api-endpoint=${KEYCLOAK_API_ENDPOINT:http://[::1]:8081}

# credentials settings
keycloak.credentials.admin-realm=${KEYCLOAK_CREDENTIALS_ADMIN_REALM:master}
keycloak.credentials.admin-username=${KEYCLOAK_CREDENTIALS_ADMIN_USERNAME:admin}
keycloak.credentials.admin-password=${KEYCLOAK_CREDENTIALS_ADMIN_PASSWORD:password}
keycloak.credentials.admin-client-id=${KEYCLOAK_CREDENTIALS_ADMIN_CLIENT_ID:admin-cli}

# authorization settings
keycloak.authorization.url=${KEYCLOAK_AUTHORIZATION_URL:http://[::1]:8081}
keycloak.authorization.response-type=${KEYCLOAK_AUTHORIZATION_RESPONSE_TYPE:code}
keycloak.authorization.scope=${KEYCLOAK_AUTHORIZATION_SCOPE:openid}
keycloak.authorization.code-challenge-method=${KEYCLOAK_AUTHORIZATION_CODE_CHALLENGE_METHOD:S256}

# -----------------------------------------
# OpenFGA properties
# -----------------------------------------
# OpenFGA settings
openfga.api-endpoint=${OPENFGA_API_ENDPOINT:http://[::1]:8080}
openfga.preshared-key=${OPENFGA_PRESHARED_KEY:preshared}

# -----------------------------------------
# Spring Boot Actuator CORS properties
# -----------------------------------------
management.endpoints.web.cors.allowed-origins=${MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOWED_ORIGINS:http://localhost:3000}
management.endpoints.web.cors.allow-credentials=${MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOW_CREDENTIALS:true}
management.endpoints.web.cors.allowed-origin-patterns=${MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOWED_ORIGIN_PATTERNS:/**}

