# -----------------------------------------
# Github Action Workflows settings
# -----------------------------------------
## connect to database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/db_ods
spring.datasource.username=app_ods
spring.datasource.password=P@ssw0rd1234

# Hibernate Dialect settings
spring.sql.init.mode=never

# CORS settings
#management.endpoints.web.cors.allowed-origins=http://localhost:3000
#management.endpoints.web.cors.allow-credentials=true
#management.endpoints.web.cors.allowed-origin-patterns=/**

# Enable IP restriction
ods.enable-ip-restriction=false

# Database SSL settings
ods.database-ssl=false
ods.database-ssl-mode=disable

# Application log level (TRACE/DEBUG/INFO/WARN)
logging.level.com.ods.*=INFO
# spring framework Log level
logging.level.org.springframework.web=info
# PostgreSQL log level
logging.level.org.postgresql=INFO
