# -----------------------------------------
# System properties
# -----------------------------------------
spring.application.name=user_authentication
# Disable Spring Boot's default error handler
server.error.whitelabel.enabled=false
server.error.path=/error
# Disable static resource mappings
spring.web.resources.add-mappings=false
# Enable Open-In-View to prevent database queries during view rendering, to suppress runtime warning
spring.jpa.open-in-view=true
# DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property.
spring.jpa.hibernate.ddl-auto=none

# Hibernate Dialect settings (always/never/embedded)
spring.sql.init.mode=never
# Enable ANSI colors in the console output (always/never/detect)
spring.output.ansi.enabled=detect

# -----------------------------------------
# Logging properties
# -----------------------------------------
# log
logging.file.name=logs/user_authentication.log
# Application log level (TRACE/DEBUG/INFO/WARN)
logging.level.com.ods.*=INFO
# spring framework Log level
logging.level.org.springframework.web=info
# PostgreSQL log level
logging.level.org.postgresql=INFO
# Show SQL statements in the log
spring.jpa.show-sql=false

# Enable detailed request logging
spring.mvc.log-request-details=true


# -----------------------------------------
# Database properties
# -----------------------------------------
# datasource settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/db_ods
spring.datasource.username=app_ods
spring.datasource.password=P@ssw0rd1234

# -----------------------------------------
# ODS Application properties
# -----------------------------------------
# Enable IP restriction
ods.enable-ip-restriction=true
# Dataabase SSL connection
ods.database-ssl=true
ods.database-ssl-mode=require
# effective end date default value
ods.default-effective-end-date=9999-12-31

# -----------------------------------------
# KeyCloak properties
# -----------------------------------------
# KeyCloak settings
keycloak.realm=master
keycloak.api-endpoint=http://[::1]:8081

# credentials settings
keycloak.credentials.admin-realm=master
keycloak.credentials.admin-username=admin
keycloak.credentials.admin-password=password
keycloak.credentials.admin-client-id=admin-cli

# authorization settings
keycloak.authorization.url=http://[::1]:8081
keycloak.authorization.response-type=code
keycloak.authorization.scope=openid
keycloak.authorization.code-challenge-method=S256

